### ISSUE TITLE
Foundation integration: does it work?

### ISSUE THREAD

**Issue by smartm0use** [shibbir/generator-angular2-typescript#16]
I installed the package selecting Foundation. Then I tried to use some Foundation code, but it doesn't work.
For example if I put inside the template of a component the code for creating a slider (http://foundation.zurb.com/sites/docs/slider.html) it doesn't work.

Why? Shouldn't it work? Otherwise why we import Foundation JS file?

**Comment by shibbir** [comment]
Hi @smartm0use, Which loader did you choose? Webpack or SystemJS ?

**Comment by smartm0use** [comment]
SystemJS. Thank you.
