### ISSUE TITLE
Unable to debug on vscode

### ISSUE THREAD

**Issue by filipedelmonte** [shibbir/generator-angular2-typescript#22]
I am trying to debug Typescript on vscode using this launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        },
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true
        }
    ]
}
```

The connection works but the breakpoints don't (“Breakpoint ignored becasue generated code not found”).

do I have to specify the directory where the .map files are?

**Comment by shibbir** [comment]
Hey @filipedelmonte, Please check these to get started:
- https://code.visualstudio.com/blogs/2016/02/23/introducing-chrome-debugger-for-vs-code
- https://github.com/Microsoft/vscode-chrome-debug

And yes I think you can debug **TypeScript**, via source maps.
