### ISSUE TITLE
"ENOENT: no such file or directory" with production task

### ISSUE THREAD

**Issue by smartm0use** [shibbir/generator-angular2-typescript#24]
Hello, i tried to see the output of the production task and i run the `build:prod` task.
But i get some `No such file or directory` errors.

Here you can see the full log:

http://pastebin.com/2mHRAWW1

**Comment by shibbir** [comment]
Hey @smartm0use, I've released a new patch [#5c74f7b](https://github.com/shibbir/generator-angular2-typescript/commit/5c74f7b78b558ee994182a3096e0764b1e3676bb)

Please install the latest version and check if that's solve the problem.

**Comment by shibbir** [comment]
@smartm0use, I've merged your changes. Can you please check and close the issue.
