### ISSUE TITLE
Provide a "None" option in addition to Bootstrap / Foundation?

### ISSUE THREAD

**Issue by Meligy** [shibbir/generator-angular2-typescript#3]
That would be nice for the simplistic projects, or projects that do not agree with all the pieces in the bootstrap implementation.

Open for discussion and might be worth splitting but:
- If I'm using Bootstrap CSS with Angular 2, I'm less likely to use the bootstrap JS and jQuery.  
  I might use something like [ng2-bootstrap](https://valor-software.com/ng2-bootstrap/#/), or nothing at all
- Maybe I do not want bootstrap at all
- The current _if_ usages in templates seem to be a bit hard to manage for a 3rd option.  
  Looks like using a folder structure for these would be better, not sure.  
  I haven't written the code though so maybe not a good judgement

**Comment by shibbir** [comment]
Fixed with [#6d55abb](https://github.com/shibbir/generator-angular2-typescript/commit/6d55abb3a5aaea7d44e8734f4d590beccf6b0837)
