### ISSUE TITLE
tsc and tsc -w

### ISSUE THREAD

**Issue by smartm0use** [shibbir/generator-angular2-typescript#6]
Hello, i installed your package with Yeoman and i had a look to gulpfile.js:

`gulp.task('server', plugins.shell.task('tsc && concurrently \"npm run tsc:w\" \"npm run lite\" '));`

Can you tell me why `tsc` run twice?
Isn't better run only `tsc -w`?

`gulp.task('server', plugins.shell.task('concurrently \"npm run tsc:w\" \"npm run lite\" '));`

And what about to add `"compileOnSave": true,` in `tsconfig.json` (as described [here](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)) in order to use `tsc` with no "watch mode"?

`gulp.task('server', plugins.shell.task('concurrently \"npm run tsc\" \"npm run lite\" '));`

**Comment by shibbir** [comment]
The reason behind `tsc && concurrently \"npm run tsc:w\" \"npm run lite\"` is that you if have to first ensure that the `"*.ts"` files don't have any errors before you actually start the server. The `tsc` command will fail if you have any errors in your source file and that would eventually stop the `lite-server` to start. Without first compiling the source files with `tsc`, the server will start anyway, whether there're any problems or not.

And the `"compileOnSave": true` option seems have some limitation according to the docs.

> This feature is currently supported in Visual Studio 2015 with TypeScript 1.8.4 and above, and atom-typescript plugin.
