### ISSUE TITLE
Couldn't select CSS framework

### ISSUE THREAD

**Issue by hazeeb** [shibbir/generator-angular2-typescript#7]
I couldn't select CSS framework using arrow keys, and eventually "none" was selected.
When i pressed down arrow key,nothing changes ,  it stopped at "None" and couldn't change the option. 
But Module loader could be selected using arrow keys.

**Comment by shibbir** [comment]
@hazeeb, still an issue?

**Comment by shibbir** [comment]
Closed as not reproducible.
